celery mode
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
products imported successfully
celery mode
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
products imported successfully
celery mode
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
Product creation error occurred: UNIQUE constraint failed: productapp_product.name
products imported successfully
task completed successfully
404 GET /task/d4f54ea0-6994-4a0f-9d92-19c0598875ce (::1): Unknown task 'd4f54ea0-6994-4a0f-9d92-19c0598875ce'
401 GET /api/workers?refresh=1 (::1): FLOWER_UNAUTHENTICATED_API environment variable is required to enable API without authentication
Visit me at http://0.0.0.0:5555
Broker: redis://localhost:6379/0
Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'productapp.tasks.run_my_command',
 'productproject.celery.debug_task']
Connected to redis://localhost:6379/0
Visit me at http://0.0.0.0:5555
Broker: redis://localhost:6379/0
Registered tasks: 
['celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'productapp.tasks.run_my_command',
 'productproject.celery.debug_task']
Connected to redis://localhost:6379/0
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productproject\settings.py changed, reloading.
Watching for file changes with StatReloader
Unauthorized: /cu-order/
Unauthorized: /cu-product/
Not Found: /rud-product/3/
Internal Server Error: /cu-order/
Traceback (most recent call last):
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 39, in list
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 100, in _wrapped_view
    orders = view_func(request, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 126, in get_queryset
    queryset = Orders.objects.select_related('customer').filter(user=self.rquest.user)
                                                                     ^^^^^^^^^^^
AttributeError: 'OrdersListCreateView' object has no attribute 'rquest'
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /cu-order/
Traceback (most recent call last):
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 39, in list
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 100, in _wrapped_view
    orders = view_func(request, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 126, in get_queryset
    queryset = Orders.objects.select_related('customer').filter(user=self.request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: amount, customer, customer_id, id, products, seller, seller_id
Internal Server Error: /cu-order/
Traceback (most recent call last):
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 39, in list
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 100, in _wrapped_view
    orders = view_func(request, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 126, in get_queryset
    queryset = Orders.objects.select_related('customer').filter(user=self.request.user)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: amount, customer, customer_id, id, products, seller, seller_id
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /rud-product/
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\venv\Lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 39, in list
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 27, in get_queryset
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 27, in get_queryset
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 27, in get_queryset
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 951 more times]
  File "C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py", line 26, in get_queryset
    print(f"mixin called for qs {self.request.method}")
RecursionError: maximum recursion depth exceeded while calling a Python object
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /product/
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /product/
Not Found: /favicon.ico
Bad Request: /product/
Bad Request: /product/
Not Found: /cu-product/
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\DHEERAJ\Desktop\codezen\productproject\productapp\views.py changed, reloading.
Watching for file changes with StatReloader
